export { Pencil as PencilIcon } from 'lucide-react'
export { Box as CubeIcon } from 'lucide-react'
export { Building as BuildingIcon } from 'lucide-react'
export { DoorOpen as DoorIcon } from 'lucide-react'
export { Type as TextIcon } from 'lucide-react'
export { Edit3 as EditIcon } from 'lucide-react'
export { Settings as SettingsIcon } from 'lucide-react'
export { Download as DownloadIcon } from 'lucide-react'
